// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF8vFtaTSgjxxM3xWbAlfztRFD-zA-Mr0',
    appId: '1:1095256349838:android:d172b69e3c5818ccab7ddf',
    messagingSenderId: '1095256349838',
    projectId: 'fir-course-2e261',
    databaseURL: 'https://fir-course-2e261-default-rtdb.firebaseio.com',
    storageBucket: 'fir-course-2e261.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuxxH2ATCUCkpaWZwp14-5_AA3ITkvmC4',
    appId: '1:1095256349838:ios:0243bd2f85b0f8adab7ddf',
    messagingSenderId: '1095256349838',
    projectId: 'fir-course-2e261',
    databaseURL: 'https://fir-course-2e261-default-rtdb.firebaseio.com',
    storageBucket: 'fir-course-2e261.appspot.com',
    iosBundleId: 'com.chatlinc.chatlinc',
  );
}
